server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

jwt:
  secret: ${jwt-secret}
  expiration: 1800  # in seconds

management:
  endpoints:
    web:
      exposure:
        include: health, info, routes
  endpoint:
    health:
      show-details: always
  server:
    port: 8762