server:
  port: 8082

spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/socialbondnetdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

rabbitmq:
  queue:
    name: javaguides
  json:
    name: javaguides_json
  exchange:
    name: javaguides_exchange
  routing:
    key: javaguides_routing_key
    json:
        key: javaguides_routing_json_key
